apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ptsxi2zyo-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:432d4a807615ee4947bd36da5b7f3847c0bf3140@sha256:337f0c84f13cc130b11ae360e4dfe69ccad1fb48cabdb12e5ce8016fc0d3442f
          name: container-image
